version: '3'

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'customerapi'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'JesusChrist1995#'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    volumes:
      - /c/Exercises/dockerFiles/customerVolumes:/var/lib/mysql
    networks:
      - smartbin-network


  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: "db"
      PMA_ARBITRARY: 1
      PMA_USER: "root"
      PMA_PASSWORD: "JesusChrist1995#"
    restart: always
    ports:
      - "8085:80"
    volumes:
      - /sessions
    networks:
      - smartbin-network

  customerapp:
    build: ./customerapi
    container_name: customerapp
    ports:
      - 8080:8080
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: JesusChrist1995#
      MYSQL_PORT: 3306
    networks:
      - smartbin-network
  
  react-app:
    build: ./reactjs/react-frontend
    container_name: react-app
    ports:
      - 3000:3000
    restart: always
    links:
      - customerapp
    networks:
      - smartbin-network


volumes:
  spring_boot_mysql_database_data:

networks:
  smartbin-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16